# Generated by Django 3.1.3 on 2021-04-26 12:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0004_post_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='image',
        ),
    ]
